#!/usr/bin/env python3
"""Emit the MSVC + Windows SDK environment for this machine as a shell snippet.

`cmd.exe` is blocked in this environment, so `vcvars64.bat` cannot be sourced
directly. This reconstructs the same INCLUDE / LIB / PATH that
"x64 Native Tools Command Prompt for VS 2022" would set, pinning the MSVC
toolset version explicitly.

Pinning matters: AMD clang rejects the two-argument <cmath> builtins
(isgreater, isless, ...) in HIP device code when they are constexpr, which is
how MSVC 14.51 (VS 2026) declares them. 14.44 (VS 2022) declares them inline and
compiles. 14.44 is the version that ships with Visual Studio 2022.

Usage:  python msvc_env.py --msvc-version 14.44.35207 > env.sh
"""

import argparse
import os
import sys

VS_CANDIDATES = [
    r"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools",
    r"C:\Program Files\Microsoft Visual Studio\2022\Community",
    r"C:\Program Files\Microsoft Visual Studio\2022\Professional",
    r"C:\Program Files\Microsoft Visual Studio\2022\Enterprise",
]

SDK_ROOTS = [
    r"C:\Program Files (x86)\Windows Kits\10",
    r"C:\Program Files\Windows Kits\10",
]


def find_msvc(version: str):
    best = None
    for vs in VS_CANDIDATES:
        tools = os.path.join(vs, "VC", "Tools", "MSVC")
        if not os.path.isdir(tools):
            continue
        for name in sorted(os.listdir(tools), reverse=True):
            full = os.path.join(tools, name)
            if not os.path.isdir(full):
                continue
            if version and not name.startswith(version):
                continue
            if os.path.isfile(os.path.join(full, "include", "cmath")):
                return full
            best = best or full
    return best


def newest_sdk():
    for root in SDK_ROOTS:
        inc = os.path.join(root, "Include")
        if not os.path.isdir(inc):
            continue
        vers = [v for v in os.listdir(inc) if os.path.isdir(os.path.join(inc, v))]
        if not vers:
            continue
        # Windows SDK versions sort lexicographically well enough (10.0.26100.0)
        ver = sorted(vers)[-1]
        return root, ver
    return None, None


def main():
    # Emit LF-only endings: this file is sourced by bash, and a stray CR would
    # be glued onto the last INCLUDE / LIB entry.
    try:
        sys.stdout.reconfigure(newline="\n")
    except Exception:
        pass

    ap = argparse.ArgumentParser()
    ap.add_argument("--msvc-version", default="14.44.",
                    help="MSVC toolset version prefix to pin (default 14.44.)")
    ap.add_argument("--extra-path", action="append", default=[],
                    help="additional PATH entries to prepend")
    args = ap.parse_args()

    msvc = find_msvc(args.msvc_version)
    if not msvc:
        print("ERROR: MSVC toolset matching %r not found" % args.msvc_version,
              file=sys.stderr)
        return 2
    sdk_root, sdk_ver = newest_sdk()
    if not sdk_root:
        print("ERROR: Windows SDK not found", file=sys.stderr)
        return 2

    inc = [os.path.join(msvc, "include")]
    lib = [os.path.join(msvc, "lib", "x64")]
    path = [os.path.join(msvc, "bin", "Hostx64", "x64")]

    sdk_inc = os.path.join(sdk_root, "Include", sdk_ver)
    for sub in ("ucrt", "shared", "um", "winrt", "cppwinrt"):
        d = os.path.join(sdk_inc, sub)
        if os.path.isdir(d):
            inc.append(d)

    sdk_lib = os.path.join(sdk_root, "Lib", sdk_ver)
    for sub in (("ucrt", "x64"), ("um", "x64")):
        d = os.path.join(sdk_lib, *sub)
        if os.path.isdir(d):
            lib.append(d)

    msvc_bin = os.path.join(msvc, "bin", "Hostx64", "x64")

    print("# generated by msvc_env.py -- MSVC %s / Windows SDK %s"
          % (os.path.basename(msvc), sdk_ver))
    # INCLUDE / LIB are what vcvars64.bat really contributes here. Exporting
    # INCLUDE makes clang search this toolset's STL before the VS 2026 (14.51)
    # one it would otherwise auto-detect, without replacing PATH -- the shell
    # this runs in needs its own PATH intact.
    print("export INCLUDE='%s'" % ";".join(inc))
    print("export LIB='%s'" % ";".join(lib))
    print("export LIBPATH='%s'" % ";".join(lib))
    print("# MSVC_BIN=%s" % msvc_bin)
    print("# msvc_root=%s" % msvc)
    print("# sdk_ver=%s" % sdk_ver)
    return 0


if __name__ == "__main__":
    sys.exit(main())
